
-- Create Users Table
create table public.users (
  id bigint generated by default as identity primary key,
  username text unique not null,
  password text not null,
  role text default 'user',
  avatar text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Songs Table
create table public.songs (
  id bigint generated by default as identity primary key,
  title text not null,
  artist text not null,
  cover text,
  url text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create Messages Table
create table public.messages (
  id bigint generated by default as identity primary key,
  sender_id bigint references public.users(id) not null,
  receiver_id bigint references public.users(id),
  content text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS) - Optional for now but recommended
-- alter table public.users enable row level security;
-- alter table public.songs enable row level security;
-- alter table public.messages enable row level security;

-- Policy to allow public read access (for simplicity in this demo)
-- create policy "Public users are viewable by everyone" on public.users for select using (true);
-- create policy "Public songs are viewable by everyone" on public.songs for select using (true);
-- create policy "Public messages are viewable by everyone" on public.messages for select using (true);

-- Allow inserts (Register/Upload)
-- create policy "Anyone can insert users" on public.users for insert with check (true);
-- create policy "Anyone can insert songs" on public.songs for insert with check (true);
-- create policy "Anyone can insert messages" on public.messages for insert with check (true);

-- STORAGE SETUP
-- You must run these commands in the Supabase SQL Editor to enable file uploads.

-- 1. Create a public bucket named 'songs'
insert into storage.buckets (id, name, public) 
values ('songs', 'songs', true);

-- 2. Allow public access to view files in 'songs' bucket
create policy "Public Access" 
on storage.objects for select 
using ( bucket_id = 'songs' );

-- 3. Allow authenticated users to upload files to 'songs' bucket
-- Note: In this simple app, we are doing backend uploads, so we actually use the Service Role or Anon key with policies.
-- If using anon key from backend without user context, we might need to allow public inserts or use service key.
-- Since we use supabase-js in Node.js with the anon key, RLS policies apply.
-- Let's allow anyone to insert for simplicity of this demo, or restricted to authenticated if we passed user token (we don't pass user token to supabase client in server.js yet, we use global client).
-- So we should allow public inserts for now (or fix server to use service role key).
create policy "Public Upload" 
on storage.objects for insert 
with check ( bucket_id = 'songs' );
